### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by ElisaMin** [ElisaMin/Heizi-Flashing-Tools#20]
任务:
* ~MicaBackground Support~
* ~AccentColor~
* ~LogPanels~ Move to #31 
* ~Windows10默认颜色提取:~
```cmd
REG QUERY HKCU\Software\Microsoft\Windows\DWM\ /v AccentColor
```
20230331：
AST MonetLize done()
20230401：
FFT IFT MonetLize done()

**Comment by ElisaMin** [comment]
用api get了。
https://github.com/ElisaMin/MonetCompose

**Comment by ElisaMin** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.mayakapps.compose.windowstyler.TransparencyUtilsKt.getSkiaLayer(TransparencyUtils.kt:37)
	at com.mayakapps.compose.windowstyler.TransparencyUtilsKt.isTransparent(TransparencyUtils.kt:43)
	at com.mayakapps.compose.windowstyler.windows.WindowsWindowStyleManager._init_$lambda-0(WindowsWindowStyleManager.kt:66)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: ComposeLayer is disposed
	at androidx.compose.ui.awt.ComposeWindowDelegate.getLayer(ComposeWindowDelegate.desktop.kt:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 17 more
Exception in thread "AWT-EventQueue-0" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.mayakapps.compose.windowstyler.TransparencyUtilsKt.getSkiaLayer(TransparencyUtils.kt:37)
	at com.mayakapps.compose.windowstyler.TransparencyUtilsKt.isTransparent(TransparencyUtils.kt:43)
	at com.mayakapps.compose.windowstyler.windows.WindowsWindowStyleManager._init_$lambda-0(WindowsWindowStyleManager.kt:66)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: ComposeLayer is disposed
	at androidx.compose.ui.awt.ComposeWindowDelegate.getLayer(ComposeWindowDelegate.desktop.kt:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 17 more
DwmSetWindowAttribute(DWMWA_MICA_EFFECT) failed with result -2147024890
